version: '3.7'

services:
  web:
    build: .
    command: gunicorn chatapp.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - db


  nginx:
    build: nginx
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  static_volume:
  media_volume: