version: "3.7"

services:
  web:
    environment:
      - DJANGO_MANAGEPY_MIGRATE=on
      - DJANGO_MANAGEPY_COLLECTSTATIC=on
    image: "${WEB_IMAGE}"
    container_name: web
    command: daphne chatapp.wsgi:application --timeout 60 --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - backendnet
    mem_limit: 2.8g
    depends_on:
      - redis
  
  # daphne:
  #   environment:
  #     - DJANGO_MANAGEPY_MIGRATE=off
  #     - DJANGO_MANAGEPY_COLLECTSTATIC=off
  #   image: "${DAPHNE_IMAGE}"
  #   restart: always
  #   container_name: daphne
  #   command: daphne -b 0.0.0.0 -p 8001 chatapp.asgi:application
  #   ports:
  #     - 8001:8001
  #   networks:
  #     - backendnet
  #   mem_limit: 1.4g
  #   depends_on:
  #     - redis

  nginx:
    environment:
      - DJANGO_MANAGEPY_MIGRATE=off
      - DJANGO_MANAGEPY_COLLECTSTATIC=off
    image: "${NGINX_IMAGE}"
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
      # - ./nginx:/etc/nginx/conf.d
      # - /etc/nginx/certs:/etc/nginx/certs
      # - /var/run/docker.sock:/tmp/docker.sock:ro
      # - /etc/certbot/conf:/etc/letsencrypt
      # - /etc/certbot/www:/var/www/certbot
    ports:
      # - "443:443"
      - "80:80"
    networks:
      - backendnet
    mem_limit: 0.7g
    depends_on:
      - web
  
  redis:
    environment:
      - DJANGO_MANAGEPY_MIGRATE=off
      - DJANGO_MANAGEPY_COLLECTSTATIC=off
    image: "${REDIS_IMAGE}"
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backendnet
    volumes:
      - ./redis-volume:/data
    mem_limit: 1.4g


volumes:
  static_volume:
  media_volume:
  redis-volume:

networks:
  backendnet:
    driver: bridge