# Generated by Django 3.2.6 on 2023-07-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='InfoMessage',
        ),
    ]
